$(document).ready(function () {

    tabla_lista_precios();

});



function tabla_lista_precios() {
    var array_productos = [
        ["Hamburguesa", "Burgy", "$40", "-", "-"],
        ["Hamburguesa", "Schneck", "$85", "-", "-"],
        ["Alitas (500g)", "-", "$50", "-", "-"],
        ["Levadura fresca", "-", "-", "-", "$24"],
        ["Levadura instantánea", "-", "$23", "-", "-"],
        ["Lata de sardinas", "-", "$40", "-", "-"],
        ["Lata de atún", "-", "$45", "-", "-"],
        ["Curitas (unidad)", "-", "$4", "-", "-"],
        ["Oregano", "-", "-", "-", "$100"],
        ["Aji, ajo y peregil", "-", "-", "-", "$100"],
        ["Adobo", "-", "-", "-", "$100"],
        ["Vinagre de alcohol (500g)", "-", "$40", "-", "-"],
        ["Lata de choclo", "-", "$42", "-", "-"],
        ["Lata de arveja", "-", "$25", "-", "-"],
        ["Lata de ensalada primavera", "-", "$42", "-", "-"],
        ["Cajita de fósforo", "-", "$10", "-", "-"],
        ["Encendedor", "-", "$15", "-", "-"],
        ["Levadura instantánea", "-", "$23", "-", "-"],
        ["Royal", "-", "$23", "-", "-"],
        ["Afeitadora (amarilla)", "BIC", "$28", "-", "-"],
        ["Afeitadora (azúl)", "Gilette", "$50", "-", "-"],
        ["Hojillas", "-", "$1", "40", "-"],
        ["Cigarro", "51", "$4", "65", "-"],
        ["Cigarro", "Nevada", "$17", "115", "-"],
        ["Cigarro", "GIF", "$5", "85", "-"],
        ["Cigarro", "Coronado", "$17", "115", "-"],
        ["Tabaco", "Cerrito", "$150", "-", "-"],
        ["Whisky", "Mac Pay", "$110", "-", "-"],
        ["Mayonesa 124g", "Uruguay", "$32", "-", "-"],
        ["Mayonesa 498g", "Uruguay", "$105", "-", "-"],
        ["Ketchup 60g", "-", "$40", "-", "-"],
        ["Mostaza 50g", "-", "$20", "-", "-"],
        ["Solución para parche", "-", "$25", "-", "-"],
        ["Parches", "-", "$10", "-", "-"],
        ["Cartas", "-", "$60", "-", "-"],
        ["Lamparitas de luz", "-", "$30", "-", "-"],
        ["Avena", "-", "-", "-", "$16"],
        ["Azúcar", "-", "-", "-", "$7"],
        ["Lentejas", "-", "-", "-", "$20"],
        ["Cocoa", "-", "-", "-", "$25"],
        ["Pan rayado", "-", "-", "-", "$8"],
        ["Maicena", "-", "-", "-", "$15"],
        ["Leche en polvo", "-", "-", "-", "$35"],
        ["Comida de gato", "-", "$10", "-", "$10"],
        ["Pegamento", "Éccole", "$190", "-", "-"],
        ["Café instantáneo", "Saint", "$5", "-", "-"],
        ["Caramelos", "-", "$1", "-", "-"],
        ["Galletitas Waffle", "-", "$22", "-", "-"],
        ["Galletitas Redondas", "-", "$20", "-", "-"],
        ["Cocoita", "Saintcolet", "$5", "-", "-"],
        ["Té", "Saint", "$5", "-", "-"],
        ["Té", "Hornimans", "$6", "-", "-"],
        ["Chupa-Chupa", "-", "$5", "-", "-"],
        ["Adherente", "-", "$55", "-", "-"],
        ["Nuez moscada", "-", "$25", "-", "-"],
        ["Canela", "-", "$18", "-", "-"],
        ["Cinta adhesiva", "-", "$20", "-", "-"],
        ["Paracetamol", "-", "$10", "-", "-"],
        ["Desodorante de ambiente", "Jupiter", "$79", "-", "-"],
        ["Mata moscas y mosquitos", "Tax", "$100", "-", "-"],
        ["Mata cucarachas", "Jupiter", "$160", "-", "-"],
        ["Salsa de tomate", "Rigby", "$75", "-", "-"],
        ["Salsa blanca", "Puritas", "$30", "-", "-"],
        ["Pañales", "-", "$18", "-", "-"],
        ["Protector diario", "Mili", "$55", "-", "-"],
        ["Chupetin", "Voaloco", "$16", "-", "-"],
        ["Shampoo", "Dove", "$12", "-", "-"],
        ["Acondicionador", "Dove", "$12", "-", "-"],
        ["Acondicionador", "Sedal", "$10", "-", "-"],
        ["Shampoo", "Pantene", "$10", "-", "-"],
        ["Acondicionador", "Pantene", "$10", "-", "-"],
        ["Jugo instantáneo", "Jazz", "$15", "-", "-"],
        ["Jugo instantáneo", "Rinde 2", "$25", "-", "-"],
        ["Jugo instantáneo", "Puritas", "$12", "-", "-"],
        ["Sal", "-", "$40", "-", "-"],
        ["Aceite", "Condesa", "$70", "-", "-"],
        ["Harina 0000", "Uruguay", "$45", "-", "$5"],
        ["Harina 0", "San Agustin", "$40", "-", "$5"],
        ["Aspiral", "-", "$15", "70", "-"],
        ["Azùcar", "Azucarlito", "$55", "-", "$5"],
        ["Azùcar", "Puritas", "$48", "-", "$5"],
        ["Grasa", "-", "$46", "-", "-"],
        ["Salsa (bolsita)", "Rigby", "$45", "-", "-"],
        ["Lámen", "-", "$20", "-", "-"],
        ["Sal (100g)", "-", "$9", "-", "-"],
        ["Caldo", "-", "$12", "-", "-"],
        ["huevos", "-", "$15", "$330", "-"],
        ["Velas blancas", "-", "$10", "-", "-"],
        ["Polenta", "-", "$40", "-", "-"],
        ["Fideos (100g)", "-", "$8", "-", "-"],
        ["Fideos paquete 400g", "-", "$30", "-", "-"],
        ["Pure de papas", "-", "$40", "-", "-"],
        ["Arroz 500g", "Saman", "$35", "-", "$7"],
        ["Arroz 1kg", "Saman", "$65", "-", "$7"],
        ["Palillos", "-", "$55", "-", "-"],
        ["Velas de colores", "-", "$15", "-", "-"],
        ["Trapos de piso", "-", "$60", "-", "-"],
        ["Trapo tipo rejilla", "-", "$40", "-", "-"],
        ["Jabón en barra", "Girando Sol", "$35", "-", "-"],
        ["Jabón en barra", "Bull Dog", "$65", "$90", "-"],
        ["Quesitos", "Pimba", "$20", "-", "-"],
        ["Quesitos", "Buby", "$10", "-", "-"],
        ["Tico-tico", "-", "$10", "-", "-"],
        ["Quesito", "Bilu Top", "$20", "-", "-"],
        ["Palichips", "-", "$7", "-", "-"],
        ["Saumerio", "-", "$25", "-", "-"],
        ["Alfajor Top", "Punta Ballena", "$35", "-", "-"],
        ["Alfajor Impacto", "Punta Ballena", "$17", "-", "-"],
        ["alfajor", "Portezuelo", "$25", "-", "-"],
        ["Pasta de dientes 50g", "Colgate", "$50", "-", "-"],
        ["Cerbeza", "Schin", "$50", "-", "-"],
        ["Caramelos de miel", "-", "$2", "-", "-"],
        ["dientitos", "-", "$3", "-", "-"],
        ["Bananitas", "-", "$3", "-", "-"],
        ["Salsa de tomate", "Val", "$25", "-", "-"],
        ["Pepas", "-", "$30", "-", "-"],
        ["conos con chocolate", "Minicco", "$20", "-", "-"],
        ["Croc-Chock", "-", "$12", "-", "-"],
        ["Gomitas (tubito)", "Gomutcho", "$10", "-", "-"],
        ["Gelatinas", "-", "$5", "-", "-"],
        ["Yerba 100g", "Canarias", "$26", "-", "$23"],
        ["Yerba 250g", "Canarias", "$57", "-", "$23"],
        ["Yerba 500g", "Canarias", "$105", "-", "$23"],
        ["Yerba 70g", "Cebador", "$17", "-", "-"],
        ["Yerba 500g", "Cebador", "$85", "-", "-"],
        ["Yerba 500g", "Baldo", "$105", "-", "$23"],
        ["Galletitas saladas", "-", "$20", "$50", "-"],
        ["Jabon de tocador", "Aroma", "$30", "-", "-"],
        ["Jabon de tocador", "Dove", "$60", "-", "-"],
        ["Jabon de tocador", "Lux", "$35", "-", "-"],
        ["Jabon de tocador", "Sensus", "$25", "-", "-"],
        ["Jabon en polvo 400g", "Granby", "$35", "-", "-"],
        ["Jabon en polvo 100g", "Plumita", "$18", "-", "-"],
        ["Galletitas saladas (malteadas)", "Luna", "$70", "-", "-"],

    ];

    new DataTable('#tabla_productos', {
        data: array_productos,
        columns: [
            { title: 'Nombre' },
            { title: 'Marca' },
            { title: 'Precio (unidad)' },
            { title: 'Precio (cantidad)' },
            { title: 'Precio suelto (100g)' },
        ],
        language: {
            url: 'https://cdn.datatables.net/plug-ins/2.2.2/i18n/es-ES.json',
        },
    });
}